### ISSUE TITLE
[Bug]: JadwalPosyandu bug on date formatting

### ISSUE THREAD

**Issue by itsLeonB** [fathoor/posyandu-api#33]
### JadwalPosyandu create request
```json
{
    "posyandu_id": 1,
    "waktu_mulai": "2024-01-14T20:00:00+07:00",
    "waktu_selesai": "2024-01-15T20:00:00+07:00"
}
```

### JadwalPosyandu create response
```json
{
    "code": 201,
    "status": "Created",
    "data": {
        "id": 4,
        "posyandu": {
            "id": 1,
            "nama": "Posyandu ITS",
            "alamat": "Kampus ITS",
            "foto": "/storage/image/posyandu.png"
        },
        "waktu_mulai": "2024-01-14 20:00:00",
        "waktu_selesai": "2024-01-15 20:00:00"
    }
}
```

feature works as expected/intended
but when calling get all API, returned data decremented by 7 hours

### JadwalPosyandu get all response
```json
{
    "code": 200,
    "status": "OK",
    "data": [
        "_other jadwal data_",
        {
            "id": 4,
            "posyandu": {
                "id": 1,
                "nama": "Posyandu ITS",
                "alamat": "Kampus ITS",
                "foto": "/storage/image/posyandu.png"
            },
            "waktu_mulai": "2024-01-14 13:00:00",
            "waktu_selesai": "2024-01-15 13:00:00"
        }
    ]
}
```

maybe format date diseragamin aja? semua `yyyy-mm-dd HH:mm:ss` atau `yyyy-mm-ddTHH:mm:ss+07:00`

**Comment by fathoor** [comment]
Server-side problem, sepertinya database server belum di set timezone nya jadi Asia/Jakarta (+7)

**Comment by fathoor** [comment]
### Fix

Issue Resolved

Request
```json
{
    "posyandu_id": 1,
    "waktu_mulai": "2024-01-29T20:00:00+07:00",
    "waktu_selesai": "2024-01-29T21:00:00+07:00"
}
```

Response
```json
{
    "code": 201,
    "status": "Created",
    "data": {
        "id": 5,
        "posyandu": {
            "id": 1,
            "nama": "Posyandu ITS",
            "alamat": "Kampus ITS",
            "foto": "/storage/image/posyandu.png"
        },
        "waktu_mulai": "2024-01-29 20:00:00",
        "waktu_selesai": "2024-01-29 21:00:00"
    }
}
```

### Reason

Server database's timezone is not set to Asia/Jakarta (+7)
```sql
-- Set Timezone
SET GLOBAL time_zone = '+7:00';
```

**Comment by itsLeonB** [comment]
> ### Fix
> Issue Resolved
> 
> Request
> 
> ```json
> {
>     "posyandu_id": 1,
>     "waktu_mulai": "2024-01-29T20:00:00+07:00",
>     "waktu_selesai": "2024-01-29T21:00:00+07:00"
> }
> ```
> 
> Response
> 
> ```json
> {
>     "code": 201,
>     "status": "Created",
>     "data": {
>         "id": 5,
>         "posyandu": {
>             "id": 1,
>             "nama": "Posyandu ITS",
>             "alamat": "Kampus ITS",
>             "foto": "/storage/image/posyandu.png"
>         },
>         "waktu_mulai": "2024-01-29 20:00:00",
>         "waktu_selesai": "2024-01-29 21:00:00"
>     }
> }
> ```
> 
> ### Reason
> Server database's timezone is not set to Asia/Jakarta (+7)
> 
> ```sql
> -- Set Timezone
> SET GLOBAL time_zone = '+7:00';
> ```

Response waktu create is OK, tapi response di Get ALL masih broken
