### ISSUE TITLE
[feature request] get all kader by posyandu

### ISSUE THREAD

**Issue by itsLeonB** [fathoor/posyandu-api#47]
antara new endpoint atau getall remaja by posyandu id bisa diakses remaja juga

**Comment by fathoor** [comment]
Bisa diakses kader maksudnya? @itsLeonB

**Comment by itsLeonB** [comment]
remaja juga buat liat daftar kader yg bisa dichat @fathoor

**Comment by fathoor** [comment]
Feature fulfilled as mentioned on #53 , `kader` endpoint now goes under `/v1/kader/remaja`

`POST` : `/v1/kader/remaja` - Create remaja as kader
`GET` : `/v1/kader/remaja` - Get all remaja as kader
`GET` : `/v1/kader/remaja/:id` - Get remaja by ID as kader
`PUT` : `/v1/kader/remaja/:id` - Update remaja (not role) as kader

**Comment by itsLeonB** [comment]
kurang yg get all kader as remaja/kader @fathoor
