### ISSUE TITLE
[feature request] new table and API pemeriksaan_threshold

### ISSUE THREAD

**Issue by itsLeonB** [fathoor/posyandu-api#61]
### New table
Table name: pemeriksaan_threshold
Columns:
- parameter (string, values sesuai kolom pada pemeriksaan, unique)
- threshold (int, values untuk menentukan apakah pemeriksaan berisiko atau tidak)

| parameter    | threshold |
|--------------|-----------:|
| berat_badan  | 35        |
| tinggi_badan | 150       |
| sistole      | 55        |

parameter yang diperlukan:
"berat_badan": 35,
    "tinggi_badan": 145,
    "sistole": 100,
    "diastole": 60,
    "lingkar_lengan": 10,
    "tingkat_glukosa": 10,
    "kadar_hemoglobin": 30,

### New API
Endpoint untuk manipulate this table

- GET - Get all (public for all)
- POST - Create new entry (only for admin)
- PUT - Update entries (only for admin)
- DELETE - Delete entries (only for admin)

**Comment by fathoor** [comment]
Threshold aku buat jadi `DECIMAL` aja ya, nyesuain tabel pemeriksaan biar nge compare value nya lebih mudah
```sql
-- Pemeriksaan
CREATE TABLE pemeriksaan (
    id INT PRIMARY KEY AUTO_INCREMENT,
    posyandu_id INT NOT NULL,
    remaja_id INT NOT NULL,
    berat_badan DECIMAL,
    tinggi_badan DECIMAL,
    sistole DECIMAL,
    diastole DECIMAL,
    lingkar_lengan DECIMAL,
    tingkat_glukosa DECIMAL,
    kadar_hemoglobin DECIMAL,
    pemberian_fe BOOL DEFAULT FALSE,
    waktu_pengukuran DATETIME NOT NULL,
    kondisi_umum ENUM('baik', 'cukup', 'lemah', '-') DEFAULT '-',
    keterangan TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (posyandu_id) REFERENCES posyandu(id) ON DELETE CASCADE,
    FOREIGN KEY (remaja_id) REFERENCES remaja(id) ON DELETE CASCADE
) ENGINE = InnoDB;
```
