### ISSUE TITLE
[Feature Request] kader is unauthorized

### ISSUE THREAD

**Issue by itsLeonB** [fathoor/posyandu-api#65]
kader role is unauthorized in these routes
- GET /user/{id}
- GET /pemeriksaan/remaja/{id}
- POST /user/register
- POST /remaja

**Comment by fathoor** [comment]
@itsLeonB 

- GET `/v1/user/:id`
Intended to only accessible by bidan or admin, will update it to give kader access too

- GET `/v1/pemeriksaan/:id`
Endpoint for kader is `/v1/kader/pemeriksaan/:id`
```json
{
    "code": 201,
    "status": "Created",
    "data": {
        "id": 4,
        <hidden>
    {
}
```

- POST `/v1/user/register`
Also intended to only accessible by bidan or admin, will update it to allow kader too

- POST `/v1/remaja`
Endpoint for kader is `/v1/kader/remaja`
```json
{
    "code": 201,
    "status": "Created",
    "data": {
        <hidden>
    {
}
```

**Comment by fathoor** [comment]
Please refer to newly added documentation for kader endpoint

<img width="970" alt="image" src="https://github.com/fathoor/posyandu-api/assets/90760976/2e4f348f-c2ab-44c0-904a-8b165bb78804">

**Comment by itsLeonB** [comment]
@fathoor 
yang ini masih unauthorized buat kader GET `/pemeriksaan/remaja/:id` (get all pemeriksaan by remaja id)
sama kelupaan buat PUT `user/:id` allow on kader
